CREATE TABLE TABLES
(
   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT TABLES_PK PRIMARY KEY,
   conn_string VARCHAR (225) NOT NULL
)
;

CREATE TABLE ASSOCIATIONS
(
   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT ASSOCIATIONS_PK PRIMARY KEY,
   obj_id INTEGER,
   src_id INTEGER NOT NULL,
   src_tbl INTEGER NOT NULL,
   tgt_id INTEGER NOT NULL,
   tgt_tbl INTEGER NOT NULL,
   cost INTEGER NOT NULL
)
;

CREATE TABLE OBJECTS
(
   id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT objects_PK PRIMARY KEY, src VARCHAR(30), type SMALLINT
)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT obj_id_fk Foreign Key
(
   obj_id
)
REFERENCES OBJECTS (id)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT src_tables_fk Foreign Key
(
   src_tbl
)
REFERENCES TABLES (id)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT tgt_tables_fk Foreign Key
(
   tgt_tbl
)
REFERENCES TABLES (id)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT src_objects_fk Foreign Key
(
   src_id
)
REFERENCES OBJECTS (id)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT tgt_objects_fk Foreign Key
(
   tgt_id
)
REFERENCES OBJECTS (id)
;


create index objects_src_idx on objects (src);
create index objects_type_idx on objects (type);

create index assoc_obj_idx on associations(obj_id);
create index assoc_src_idx on associations(src_id);
create index assoc_tgt_idx on associations(tgt_id);
create index assoc_cost_idx on associations(cost);




// delete context and set counts to 1
delete from ASSOCIATIONS;
delete from OBJECTS;
ALTER TABLE OBJECTS ALTER id set increment by 1;
ALTER TABLE ASSOCIATIONS ALTER id set increment by 1;
ALTER TABLE k.OBJECTS ALTER COLUMN id RESTART WITH 0;
ALTER TABLE k.associations ALTER COLUMN id RESTART WITH 0;
