CREATE TABLE TABLES
(
   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT TABLES_PK PRIMARY KEY,
   conn_string VARCHAR (225) NOT NULL
)
;
INSERT INTO tables (conn_string) VALUES ('dummy');

CREATE TABLE ASSOCIATIONS
(
   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT ASSOCIATIONS_PK PRIMARY KEY,
   cell_id INTEGER,
   src_id INTEGER NOT NULL,
   src_tbl INTEGER NOT NULL,
   tgt_id INTEGER NOT NULL,
   tgt_tbl INTEGER NOT NULL,
   cost INTEGER NOT NULL
)
;

CREATE TABLE CELLS
(
   id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT cells_PK PRIMARY KEY, src VARCHAR(30), type SMALLINT
)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT cell_id_fk Foreign Key
(
   cell_id
)
REFERENCES CELLS (id)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT src_tables_fk Foreign Key
(
   src_tbl
)
REFERENCES TABLES (id)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT tgt_tables_fk Foreign Key
(
   tgt_tbl
)
REFERENCES TABLES (id)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT src_cells_fk Foreign Key
(
   src_id
)
REFERENCES CELLS (id)
;

ALTER TABLE ASSOCIATIONS ADD CONSTRAINT tgt_cells_fk Foreign Key
(
   tgt_id
)
REFERENCES CELLS (id)
;


create index cells_src_idx on CELLS (src);
create index cells_type_idx on CELLS (type);

create index assoc_cell_idx on ASSOCIATIONS(cell_id);
create index assoc_src_idx on ASSOCIATIONS(src_id);
create index assoc_tgt_idx on ASSOCIATIONS(tgt_id);
create index assoc_cost_idx on ASSOCIATIONS(cost);




--// delete context and set counts to 1
--delete from ASSOCIATIONS;
--delete from CELLS;
--ALTER TABLE CELLS ALTER id set increment by 1;
--ALTER TABLE ASSOCIATIONS ALTER id set increment by 1;
ALTER TABLE CELLS ALTER COLUMN id RESTART WITH 0;
ALTER TABLE ASSOCIATIONS ALTER COLUMN id RESTART WITH 0;

--commit;
